### ISSUE TITLE
EntitySync throwing error with 9.0-rc1

### ISSUE THREAD

**Issue by cmdflow** [altmp/altv-issues#1336]
### Description of the problem

[21:27:56] Loading resource entitysync
Unhandled exception. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.EntryPointNotFoundException: Unable to find an entry point named 'Server_SubscribeEvent' in shared library.
   at System.Runtime.InteropServices.NativeLibrary.GetSymbol(IntPtr handle, String symbolName, Boolean throwOnError)
   at System.Runtime.InteropServices.NativeLibrary.GetExport(IntPtr handle, String name)
   at AltV.Net.Native.Library..ctor()
   at AltV.Net.ModuleWrapper.MainWithAssembly(IntPtr serverPointer, IntPtr resourcePointer, AssemblyLoadContext assemblyLoadContext)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at AltV.Net.Host.Host.InitAltVAssembly(Assembly altVNetAssembly, LibArgs libArgs, AssemblyLoadContext resourceAssemblyLoadContext, String resourceName)
   at AltV.Net.Host.Host.ExecuteResource(IntPtr arg, Int32 argLength)
Aborted

### Reproduction steps

Load resource entitysync

### Expected behaviour

Should not throw error and did not before (i am a c# noob so no idea why)

### Operating system

debian 10

### Version

9.0-rc1

**Comment by FabianTerhorst** [comment]
Not all of your AltV.Net.dll's are updated.

**Comment by Konders** [comment]
> Not all of your AltV.Net.dll's are updated.

![image](https://user-images.githubusercontent.com/29742102/150567005-9b8b3419-2985-47af-a588-a5922593b0d9.png)

**Comment by FabianTerhorst** [comment]
Its for sure a outdated dll.

**Comment by C0kkie** [comment]
Its not a problem with entitysync, i use it too without problems

**Comment by cmdflow** [comment]
It is a problem of outdated dlls as Fabian and Cokkie said. Fixed it by simply replacing altv.net.dll - did not even recompile entitysync. Can confirm ist NOT a problem with entitysync

**Comment by fauconjona** [comment]
I had the exact same issue, I updated the nugget packages and it works.

**Comment by Konders** [comment]
After clearing nugget cache - everything is ok
