### ISSUE TITLE
NullReferenceException on getting vehicle health

### ISSUE THREAD

**Issue by Tsumiki-Chan** [altmp/altv-issues#1339]
### Description of the problem

(C#)
I'm not entirely sure which getter is responsible, but upon getting vehicle damage I get the following NullReferenceException.

```
       System.NullReferenceException: Object reference not set to an instance of an object.
          at System.SpanHelpers.IndexOf(Byte& searchSpace, Byte value, Int32 length)
          at System.String.Ctor(SByte* value)
          at System.Runtime.InteropServices.Marshal.PtrToStringAnsi(IntPtr ptr)
          at AltV.Net.Elements.Entities.Vehicle.get_HealthData()
```

Getters in Use:
vehicle.BodyHealth
vehicle.BodyAdditionalHealth
vehicle.EngineHealth
vehicle.PetrolTankHealth

### Reproduction steps

Researching r.n

### Expected behaviour

-

### Operating system

Debian 10

### Version

9.0-rc2

**Comment by FabianTerhorst** [comment]
Please Upgrade to latest c# Module Version.
