### ISSUE TITLE
[Chop Shop Update] New Vehicles cannot be tuned / Missing Mod Kits

### ISSUE THREAD

**Issue by chaosfreak93** [altmp/altv-issues#2146]
### Description of the problem

Currently it is not possible to apply mods to the new vehicles. If i try to set the Vehcile Mod Kit it gives me an Error.
```
[19:37:48][Error] Uncaught exception in event listener of event "playerConnected":
 Error: wrong modkit
    at file:///C:/Users/yanlu/Desktop/Coden/ttt/resources/main/server.js:137:18
    at f (file:///C:/Users/yanlu/Desktop/Coden/ttt/resources/main/server.js:31:2712)
[19:37:48][Error] [V8] Exception at main:file:///C:/Users/yanlu/Desktop/Coden/ttt/resources/main/server.js:31
[19:37:48][Error]   ${l}  `)} ${r[1]}`}ot=function(t,n=!0){let r=0;n&&(t=fo(t)),t=jn(t,"NFC");for(le...
[19:37:48][Error]   Error: wrong modkit
    at file:///C:/Users/yanlu/Desktop/Coden/ttt/resources/main/server.js:137:18
    at f (file:///C:/Users/yanlu/Desktop/Coden/ttt/resources/main/server.js:31:2712)
[19:37:48][Error] Error: wrong modkit
```

### Reproduction steps

You can use the following code on server-side to reproduce the error.
```
    const vehicleHash = alt.hash('dominator9'); // Tryed with 'turismo3', 'polgauntlet' and 'dominator9'
    let vehicle = new alt.Vehicle(vehicleHash, new alt.Vector3(103.18, 6474.87, 33.73), new alt.Vector3(0, 0, 0));
    alt.log(alt.getVehicleModelInfoByHash(vehicleHash).availableModkits) // Output: [ false, false ]
    alt.log(vehicle.modKitsCount); // Output: 0
    vehicle.modKit = 1; //Also tryed 543 with the dominator9 (found in Durty's gta-v-data-dumps)
    vehicle.setMod(VehicleModType.Engine, 1); // Error: wrong modkit
```

### Expected behaviour

Ability to set correct Mod Kit and tune new vehicles.

### Additional context

Last data binary update: 19:35:00 CET

### Operating system

Windows 10 22H2

### Version

15.66 (release)

### Confirmation of issue's presence

- [X] *By submitting this ticket, I affirm that I have verified the presence of this issue on the latest developer version available at the time of writing this ticket.*

**Comment by FabianTerhorst** [comment]
try a different vehicle from the dlc.

**Comment by FabianTerhorst** [comment]
and make sure to redownload server and data folder.

**Comment by chaosfreak93** [comment]
> and make sure to redownload server and data folder.

i'm using altv-pkg

**Comment by chaosfreak93** [comment]
> try a different vehicle from the dlc.

Tryed fr36, vigero3, asterope2, driftfuto, boxville6, police5 and terminus with different mods. Same error.

Also tryed alt:V Dev Version. alt:V Dev Version kinda works. Doesn't give me `wrong modkit` error but on the most mods `Error: mod doesn't exist`. Not related to vehicle (from the new dlc)
