### ISSUE TITLE
Synchronised Scene causes server shutdown

### ISSUE THREAD

**Issue by toyerovsky** [altmp/altv-issues#2159]
### Description of the problem

Creating and applying synchronised scene to synchronised entity such as player, ped etc. causes an instant server shutdown with following error:

System.ArgumentNullException: Value cannot be null. (Parameter 'key')
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at AltV.Net.Core.OnStartSyncedScene(IntPtr source, Int32 sceneid, Position position, Rotation rotation, UInt32 animDictHash, IntPtr[] entites, BaseObjectType[] types, UInt32[] animHashes, UInt64 size)
   at AltV.Net.ModuleWrapper.OnStartSyncedScene(IntPtr source, Int32 sceneid, Position position, Rotation rotation, UInt32 animDictHash, IntPtr[] entites, BaseObjectType[] types, UInt32[] animHashes, UInt64 size)

### Reproduction steps

1. Create a C# serverside resource with following code:

```
public class MainResource : AsyncResource
{
    public override void OnStart()
    {
        Alt.OnRequestSyncScene += (source, id) =>
        {
            return true;
        };

        Alt.OnStartSyncedScene += (source, id, position, rotation, hash, animHash) =>
        {
        };

        Alt.OnUpdateSyncedScene += (source, rate, id) =>
        {
        };

        Alt.OnStopSyncedScene += (source, id) =>
        {
        };
    }

    public override void OnStop()
    {
    }
}
```

2. Create a JavaScript clientside resource with following code:

```
on('consoleCommand', async (command) => {
    if (command == 'test') {
        await alt.Utils.requestAnimDict('amb@world_human_cheering@female_c');
        const scene = networkCreateSynchronisedScene(0, 0, 0, 0, 0, 0, 2, false, false, 0, 0, 0);
        networkAddPedToSynchronisedScene(Player.local, scene, 'amb@world_human_cheering@female_c', 'base', 0, 0, 0, 0, 0, 0);
        networkStartSynchronisedScene(scene)
    }
});
```

3. Write command "test" in console
4. Server shutdowns immediately with aforementioned error.

### Expected behaviour

Running synchronised scene won't cause server shutdown.

### Operating system

Windows

### Version

16.0.2-dev

### Confirmation of issue's presence

- [X] *By submitting this ticket, I affirm that I have verified the presence of this issue on the latest developer version available at the time of writing this ticket.*

**Comment by deluvas1911** [comment]
@Doxoh No crash on JS. Can you move it to C# repo?

**Comment by toyerovsky** [comment]
Works like a charm!
