### ISSUE TITLE
C# AltAsync.OnScriptRpc payload issue (may crash the server)

### ISSUE THREAD

**Issue by AlekseiKrivo** [altmp/altv-issues#2240]
### Description of the problem

I'm trying to create a fairly simple async method to test this feature, and I've run into a strange issue.
I have a pretty simple resource with async **TestRpc** handler

```csharp
namespace TestResource
{
    public class Starting : AsyncResource
    {
        public Starting() : base(true)
        {}
        public override void OnStart()
        {
            AltAsync.Log("STARTED!");
        }

        public override void OnStop()
        {
            throw new NotImplementedException();
        }
    }
    public sealed class Test : IScript
    {
        public Test()
        {
            AltAsync.OnScriptRpc += TestRpc;
            AltAsync.Log("TestRpc registered!");
        }
        public static async Task TestRpc(IScriptRPCEvent scriptRpcEvent, IPlayer player, string name, object[] args, ushort answerId)
        {
            AltAsync.Log(name);
            AltAsync.Log(Convert.ToString(args[0])); // args[0] becomes an empty string randomly
            scriptRpcEvent.Answer("YAY!");
        }
    }
}
```

So, when I call RPC from a **JS** client using

```js
const response = await alt.emitRpc("TestRpc", "Test payload string");
```

The registered event on the server-side is fired, **BUT** my payload string ("_Test payload string_") randomly becomes an empty string ("") in **args[0]** when I register my **TestRpc** handler using **AltAsync**. For example, if I call RPC 10 times and in 7 out of 10 cases I get an empty string. 
Also, if I send from client number or boolean (instead of string) it works correctly. I believe this is because the **string** is a **Reference Type** in **C#**.

**IMPORTANT: Sending an object from client using **alt.emitRpc** twice may crash the server.**

```
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at AltV.Net.Elements.Args.MValueConst.ToObject()
   at System.Linq.Enumerable+SelectArrayIterator`2[[AltV.Net.Elements.Args.MValueConst, AltV.Net.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ToArray()
   at AltV.Net.Async.AsyncCore+<>c__DisplayClass117_1.<OnScriptRPCEvent>b__1(AltV.Net.Async.Events.ScriptRpcAsyncDelegate)
   at AltV.Net.Async.AsyncEventHandler`1+<ExecuteEventAsync>d__4[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[AltV.Net.Async.AsyncEventHandler`1+<ExecuteEventAsync>d__4[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], AltV.Net.Async, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]](<ExecuteEventAsync>d__4<System.__Canon> ByRef)
   at AltV.Net.Async.AsyncEventHandler`1[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ExecuteEventAsync(System.__Canon, System.Func`2<System.__Canon,System.Threading.Tasks.Task>)
   at AltV.Net.Async.AsyncEventHandler`1+<CallAsync>d__2[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[AltV.Net.Async.AsyncEventHandler`1+<CallAsync>d__2[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], AltV.Net.Async, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]](<CallAsync>d__2<System.__Canon> ByRef)
   at AltV.Net.Async.AsyncCore+<>c__DisplayClass117_0+<<OnScriptRPCEvent>b__0>d.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[AltV.Net.Async.AsyncCore+<>c__DisplayClass117_0+<<OnScriptRPCEvent>b__0>d, AltV.Net.Async, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]](<<OnScriptRPCEvent>b__0>d ByRef)
   at AltV.Net.Async.AsyncCore+<>c__DisplayClass117_0.<OnScriptRPCEvent>b__0()
   at System.Threading.Tasks.Task`1[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].InnerInvoke()
   at System.Threading.Tasks.Task+<>c.<.cctor>b__272_0(System.Object)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(System.Threading.Thread, System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef, System.Threading.Thread)
   at System.Threading.Tasks.Task.ExecuteEntryUnsafe(System.Threading.Thread)
   at System.Threading.Tasks.Task.ExecuteFromThreadPool(System.Threading.Thread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool+WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
```

**IMPORTANT 2: If I register the handler with Alt (not async) all of it works correctly.**

Seems like something wrong with threading. Am I missing something?

### Reproduction steps

1. Create a simple **C#** server resource with **AltAsync.OnScriptRpc** event (or just copy my code from above).
2. Call RPC from client using **alt.emitRpc** several times
```js
const response = await alt.emitRpc("TestRpc", "Test payload string"); // This payload will become an empty string on server randomly
```

```js
const response = await alt.emitRpc("TestRpc", 123); // This payload will be received correctly every time
```

```js
const response = await alt.emitRpc("TestRpc", { foo: "bar" }); // This payload will crash the server
```
3. Look at the value of **args[0]** in TestRpc handler on server-side

### Expected behaviour

Arguments will be received correctly on the server-side.
Sending any type of argument won't cause the server to crash.

### Operating system

Windows

### Version

AltV.Net.Async 16.0.4 | alt:V Server 16.0.109 (release)

### Confirmation of issue's presence

- [X] *By submitting this ticket, I affirm that I have verified the presence of this issue on the latest developer version available at the time of writing this ticket.*

**Comment by xLuxy** [comment]
Could you please try and see if you experience the same behavior in js module?

**Comment by AlekseiKrivo** [comment]
I've try to reproduce it on JS module. It works fine with no issues on JS.

```js
const resolveAfter2Seconds = () => {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve('resolved');
    }, 2000);
  });
}

alt.onRpc('TestRpc', async (player, ...args) => {
  await resolveAfter2Seconds();
  alt.log('RPG.Server:TestRpc', player, args);
  return args;
});
```

**Comment by AlekseiKrivo** [comment]
Yep it works with 16.0.5. Thank you!
