### ISSUE TITLE
Segmentation Fault when user enteres the wrong password upon connecting

### ISSUE THREAD

**Issue by SerethiX** [altmp/altv-issues#548]
You can crash the server when you enter a wrong password in the connection dialog.

**Expected behavior**
The server should refuse the connection and continue normal operation.

**Current behavior**
The server dies instantly after refusing the connection.

**Possible solution**
None

**Steps to reproduce**
1. Setup a server running release build 1181
2. set a password.
  1. Set the server to use CDN, don't know if it matters, haven't tested yet.
3. Try to join the server with a wrong password.
4. Check the server log

**Context (environment)**
`start.sh: line 20:    33 Segmentation fault      (core dumped) LD_LIBRARY_PATH=${BASEDIR} ./altv-server`

**Detailed description**

**Possible implementation**

**Comment by Lhoerion** [comment]
Try running the server with `gdb` (GNU Debugger) and attach the result it'll output

**Comment by SerethiX** [comment]
I will, but I won't be able to make it before next week.

**Comment by Lhoerion** [comment]
@SerethiX Any news regarding this?

**Comment by SerethiX** [comment]
I have this very unspecific log:

```
Thread 38 "altv-server" received signal SIG34, Real-time event 34.
[Switching to Thread 0x7f29427fc700 (LWP 75)]
0x00007f29b956b170 in ?? ()

AND

[New Thread 0x7ffa50ff9700 (LWP 81)]
[New Thread 0x7ffa33fff700 (LWP 82)]
[New Thread 0x7ffa337fe700 (LWP 83)]

Thread 1 "altv-server" received signal SIG34, Real-time event 34.
futex_wait_cancelable (private=0, expected=0, futex_word=0x55cc969cfad4) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
88      ../sysdeps/unix/sysv/linux/futex-internal.h: No such file or directory.
```

Can you read anything from it?

Digging deeper!

**Comment by SerethiX** [comment]
When I try to connect with the wrong password:

```
free(): invalid pointer
Thread 34 "altv-server" received signal SIGABRT, Aborted.
[Switching to Thread 0x7f6de77fe700 (LWP 71)]
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
```

**Comment by FabianTerhorst** [comment]
Use ```thread apply all bt``` to get backtrace for all threads.

**Comment by SerethiX** [comment]
I have entered the wrong password and "it worked":

`Wrong password` instead of `Connection refused`. Then someone connected to the dev-branch server using the release branch. He then got "Connection refused" and the Server crashed again:

```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `./altv-server --no-module-path'.
Program terminated with signal SIGABRT, Aborted.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
[Current thread is 1 (Thread 0x7fde10ff9700 (LWP 84))]

// skipping to referenced thread call:

Thread 1 (Thread 0x7fde10ff9700 (LWP 84)):
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007fdf432a2535 in __GI_abort () at abort.c:79
#2  0x00007fdf432f9508 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7fdf4340428d "%s\n") at ../sysdeps/posix/libc_fatal.c:181
#3  0x00007fdf432ffc1a in malloc_printerr (str=str@entry=0x7fdf4340243b "free(): invalid pointer") at malloc.c:5341
#4  0x00007fdf4330142c in _int_free (av=<optimized out>, p=<optimized out>, have_lock=<optimized out>) at malloc.c:4165
#5  0x000056553744d4e2 in alt::CRefCountable::RemoveRef() const ()
#6  0x00007fdf40852d55 in Player_RemoveRef (player=<optimized out>) at /usr/include/c++/8/bits/unordered_set.h:97
#7  0x00007fdec672ab2c in ?? ()
#8  0x00000000cd4a3429 in ?? ()
#9  0x00007fdf3b78e718 in vtable for InlinedCallFrame () from /usr/share/dotnet/shared/Microsoft.NETCore.App/3.1.4/libcoreclr.so
#10 0x00007fde10ff4c90 in ?? ()
#11 0x00007fdec2d11500 in ?? ()
#12 0x0000000900000001 in ?? ()
#13 0x00007fde10ff4590 in ?? ()
#14 0x00007fdec672ab2c in ?? ()
#15 0x00007fde10ff4600 in ?? ()
#16 0x0000000000000000 in ?? ()
```

**Comment by FabianTerhorst** [comment]
This doesn't happen anymore since some time ago.
